name: flutter_qq
description: Flutter plugin for QQ.
version: 0.0.5
author: marekchen<c491843272@gmail.com>
homepage: https://github.com/marekchen/flutter_qq

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  image_picker: ^0.6.0+15

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.github.marekchen.flutterqq
    pluginClass: FlutterQqPlugin

environment:
  sdk: ">=2.1.0 <3.0.0"
